services:
  - type: web
    name: layoutcraft-backend
    env: docker
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: ENV
        value: production